version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"   # Jenkins Web UI
      - "50000:50000" # Agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
volumes:
  jenkins_home: